version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: nhattr/react-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: USER
          docker-password: PASS
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo 'composer install'
            echo 'docker-compose down'
            echo 'docker-compose pull'
            echo 'docker-compose up -d'
workflows:
  my-pipeline:
    jobs:
      - node/test
      - build-and-push:
          type: approval
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
